### PR TITLE
Attempt to translate hyphened names if provided

### PR DESCRIPTION
**Pull request by tombailey**

### CODE REVIEW

**Comment by rturk** [comment]
Hi @tombailey. Thanks! Interesting, we'll review with the team.

**Comment by tombailey** [comment]
@rturk any update on this?

**Comment by rturk** [comment]
@tombailey can you also add some tests?

**Comment by tombailey** [comment]
@rturk sorry for the delay. Now with tests as requested

**Comment by sibelius** [comment]
@tombailey great work on this

sorry for the long time to merge this

best

**Pull request merged**
